### ISSUE TITLE
Scale Modal - Heading shown as ToolTip anywhere

### ISSUE THREAD

**Issue by UBOrange** [telekom/scale#666] opened 2021-11-02 16:17 UTC
We are using the Scale "Modal" component.
It displays the heading of the modal as ToolTip (mouse over) anywhere. Please see the attached screenshot.
Expected behaviour: It should not do so.
![Screenshot_Heading_displayed_anywhere](https://user-images.githubusercontent.com/88503149/139903547-0907659f-32ca-4f3d-8323-7f31e9551ee4.png)

**Comment by acstll** [comment] 2021-11-03 16:40
Thank you @UBOrange for opening this.

This looks like a bug. So, to confirm this, anywhere you put the mouse it will display a tooltip with the content of the heading. Is that correct?

**Comment by acstll** [comment] 2021-11-04 11:00
I can confirm this. But I'm not sure it is a bug since it's meant to be there for accessibility reasons. We will check.

**Comment by tommy-codez** [comment] 2021-12-21 13:15
Hi there,
we also found this behavior. If this is intended, it would be nice to have the possibility to disable it. Because its quite irritating for the user to have this tooltip on closing buttons/fields etc..

Thank you!

**Comment by acstll** [comment] 2021-12-21 13:52
We're having an accessibility sprint in January, so we'll address this issue latest by then.

Thanks for the feedback @tommy-codez

**Closed** 2022-02-08 09:50 UTC
Labels: bug
