### ISSUE TITLE
scale-app-header rendering bug 🐛 

### ISSUE THREAD

**Issue by MrChaosXx** [telekom/scale#1002] opened 2022-04-20 11:50 UTC
Hello together,

I found a rendering bug from the scale-app-header.
At a width of 1023px the header renders over the whole page:
![image](https://user-images.githubusercontent.com/90321106/164224019-6bbff2ea-53bd-4b97-bd22-73bfe9709435.png)

I also saw the bug on other websites, which are using the scale header.

best regards
Paul

**Comment by nowseemee** [comment] 2022-04-20 13:45
Hi Paul, thanks for opening this question. It looks like the library is not initialized. Are you sure it's [properly](https://github.com/telekom/scale#setup-with-a-bundler-or-es-modules) set up? If yes, could you please provide a code sandbox example reproduction of the bug? Thanks!

**Comment by MrChaosXx** [comment] 2022-05-02 12:07
Hi @nowseemee ,
sorry for the late reply. At the moment I am very busy at work and with my studies. I will try to set up a project for you next week.
I hope that this is not too late.

**Comment by nowseemee** [comment] 2022-05-12 08:38
hi, @MrChaosXx thanks a lot for the repo - I'll take a look and get back to you.

**Comment by nowseemee** [comment] 2022-05-21 18:09
hey Paul, could you share the repo again? Thanks!

**Comment by MrChaosXx** [comment] 2022-05-23 12:24
Is out :)

**Comment by acstll** [comment] 2022-06-30 17:34
This seems to be fixed (tested with the latest version).

What did you exactly mean with "is out" 🤓? @MrChaosXx

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/851105/176741282-b5addd5b-9732-41ed-888d-364acf690aa8.png">

**Comment by acstll** [comment] 2022-07-15 07:59
Closing this assuming it's all good, please re-open or get in touch if not. Thanks again for your feedback @MrChaosXx 💜

**Closed by acstll** 2022-07-15 07:59 UTC
Labels: bug
