### ISSUE TITLE
Build failing in Angular and React with the latest Scale version 3.0.0-beta.135

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#2040] opened 2023-06-23 09:32 UTC
**Scale Version**
    `"@telekom/scale-components": "^3.0.0-beta.135",`

**Framework and version**
    `"@angular/cli": "~16.1.1",`

**Current Behavior**

Intermittent error while building app:

```
 ng build
✔ Browser application bundle generation complete.

./node_modules/@telekom/scale-components/dist/scale-components/scale-components.css - Error: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
/home/mato/test-scale/node_modules/@telekom/scale-components/dist/scale-components/scale-components.css:1:80: Can't resolve './fonts/TeleNeoWeb/TeleNeoWeb-Ultra.eot' in '/home/mato/test-scale/node_modules/@telekom/scale-components/dist/scale-components'

./node_modules/@telekom/scale-components/dist/scale-components/scale-components.css - Error: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
/home/mato/test-scale/node_modules/@telekom/scale-components/dist/scale-components/scale-components.css:1:131: Can't resolve './fonts/TeleNeoWeb/TeleNeoWeb-Ultra.woff' in '/home/mato/test-scale/node_modules/@telekom/scale-components/dist/scale-components'

./node_modules/@telekom/scale-components/dist/scale-components/scale-components.css - Error: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
/home/mato/test-scale/node_modules/@telekom/scale-components/dist/scale-components/scale-components.css:2:10: Can't resolve './fonts/TeleNeoWeb/TeleNeoWeb-Ultra.woff2' in '/home/mato/test-scale/node_modules/@telekom/scale-components/dist/scale-components'

./node_modules/@telekom/scale-components/dist/scale-components/scale-components.css - Error: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
/home/mato/test-scale/node_modules/@telekom/scale-components/dist/scale-components/scale-components.css:2:149: Can't resolve './fonts/TeleNeoWeb/TeleNeoWeb-UltraItalic.eot' in '/home/mato/test-scale/node_modules/@telekom/scale-components/dist/scale-components'

./node_modules/@telekom/scale-components/dist/scale-components/scale-components.css - Error: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
/home/mato/test-scale/node_modules/@telekom/scale-components/dist/scale-components/scale-components.css:2:206: Can't resolve './fonts/TeleNeoWeb/TeleNeoWeb-UltraItalic.woff' in '/home/mato/test-scale/node_modules/@telekom/scale-components/dist/scale-components'

./node_modules/@telekom/scale-components/dist/scale-components/scale-components.css - Error: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
/home/mato/test-scale/node_modules/@telekom/scale-components/dist/scale-components/scale-components.css:3:10: Can't resolve './fonts/TeleNeoWeb/TeleNeoWeb-UltraItalic.woff2' in '/home/mato/test-scale/node_modules/@telekom/scale-components/dist/scale-components'

```

## Steps to reproduce

- `npm install -g @angular/cli`
- `ng new --inline-style --inline-template --routing true --standalone --style css test-scale`
- follow the setup in https://telekom.github.io/scale/?path=/docs/setup-info-scale-and-angular--page
- `ng build`

**Comment by tommy-codez** [comment] 2023-06-23 18:51
I also got this bugs with scale version 135 and react. 
Are there any new requirements where to install the new Version of TeleNeo fonts ? (currently we use an older version of this fonts)

**Comment by georgwittberger-telekom-mms** [comment] 2023-06-26 07:41
We can confirm this problem using React 18.2.0 (based on create-react-app) and @telekom/scale-components-react@3.0.0-beta.135.

It just seems like the files for the newly introduced font variant "Ultra" are missing in this package directory:

`@telekom/scale-components/dist/scale-components/fonts/TeleNeoWeb`

This is a blocker for us, so we cannot use beta.135.

**Comment by felix-ico** [comment] 2023-06-26 11:21
Hi @mato-a @tommy-codez @georgwittberger-telekom-mms thanks for pointing this out, this looks like an oversight on our part, i have opened a PR to fix this https://github.com/telekom/scale/pull/2041

**Comment by felix-ico** [comment] 2023-06-27 10:25
this is fixed with the latest release beta.136, thanks again for pointing this out

**Closed by felix-ico** 2023-06-27 10:25 UTC
Labels: bug

**Comment by acstll** [comment] 2023-07-03 08:24
Sorry @mato-a and @georgwittberger-telekom-mms, this was my bad 🙏 — https://github.com/telekom/scale/pull/2025 👀

(thank you @felix-ico for the fix!)

---
@georgwittberger-telekom-mms I also wanted to mention that in the latest release the Notification components (except for the Badge) were merged into [a single one](https://telekom.github.io/scale/?path=/docs/beta-components-notification--standard). We tried and made sure there were no regressions. Any feedback from your side would be highly appreciated, as always.
