### ISSUE TITLE
No "clean" way for DefaultValue in DropDown?

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#868] opened 2022-02-14 15:23 UTC
Hi there,

we have some issues with the Dropdown, setting a default value. It seems the dropdown always select the last entry in the list of options.

When we use the methods like in the doc examples (selected on an option), we get a lot of warnings in our console. 

`(Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.)`

But how is the defaultValue correctly set?

I created an example of this on https://codesandbox.io/s/dropdown-default-value-42mvl

Thanks,

**Comment by maomaoZH** [comment] 2022-02-16 08:23
Hi @tommy-codez, if I understand your question correctly, that you would like to set a re-select/default select value. In this case, you can pass the value to `scale-dropdown` component.
```
<ScaleDropdown
    label="DropDownList1"
    name="DropDown1"
    size="small"
    id="DropDownId1"
    value={"value2"}
 >
    <option key={"key1"} value={"value1"}>
      {"Label1"}
    </option>
    <option key={"key2"} value={"value2"}>
      {"Label2"}
    </option>
    <option key={"key3"} value={"value3"}>
      {"Label3"}
    </option>
 </ScaleDropdown>
```

I hope this will help you to resolve the problem.

Cheers
Maomao

**Comment by tommy-codez** [comment] 2022-03-05 16:33
Thank you @maomaoZH , sorry for the late response. 

Your solution could eventually help, but it doestn work with empty entry.

We often use an empty entry as a default but the dropdown always select the last entry in the list.

I modified my example, on codesandbox.

**Comment by maomaoZH** [comment] 2022-03-24 13:43
Hi, @tommy-codez  I apologise that I came back to you so late! To be honest, I also don't completely get why the last option is selected when there is no pre-set value. Empty value is considered as no pre-set value. Therefore in your codesanbox, the last option is selected. The team is considering to re-write the whole implementation. But it might take some time to achieve it. For now, I could offer you a workaround: 
```
      <ScaleDropdown
          label="DropDownList1"
          name="DropDown1"
          size="small"
          id="DropDownId1"
          value={""}
        >
          <option key={"key1"} value={"value1"}>
            {"Label1"}
          </option>
          <option key={"key2"} value={"value2"}>
            {"Label2"}
          </option>
          <option key={"key3"} value={"value3"}>
            {"Label3"}
          </option>
          <option key={"key0"} value={""} hidden></option>
        </ScaleDropdown>
```
In this way, empty entry does not break the UI. 
Please feel free to leave a comment when you have more issues.

Regards,
Maomao

**Comment by maomaoZH** [comment] 2022-03-28 08:39
We noticed the issue is related to Stencil library. We have reported this issue, see here https://github.com/ionic-team/stencil/issues/3301.

**Comment by maomaoZH** [comment] 2022-05-13 06:55
We have decided to write our own dropdown components instead of using native ones. So if you don't mind, I will close this issue.

**Closed by maomaoZH** 2022-05-13 06:55 UTC
Labels: bug, react
