### ISSUE TITLE
backdrop: 'static' in modal dialog

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#428] opened 2021-06-25 14:52 UTC
Hi there,

is there an option to prevent closing a modal dialog when clicking outside the window?

(To prevent a scenario where entered data could be lost)

Cheers

**Comment by acstll** [comment] 2021-06-28 08:16
hey @tommy-codez thank you for your question.

There is no option now, but we can definitely add an attribute to disable this behaviour.

We're adding this to the backlog!

**Comment by Lalaluka** [comment] 2021-06-30 21:32
Hey,
maybe take a look at the approach I wrote in #430 🙃

**Comment by acstll** [comment] 2021-07-06 15:10
A PR with a fix for this use case has been merged, thank you @Lalaluka!

It'll be out in the next beta release.

@tommy-codez you'll be able to prevent the modal from closing like this (generic code):

```js
modal.addEventListener('scaleBeforeClose', (event) => {
  if (event.detail.trigger === 'BACKDROP') {
    event.preventDefault()
  }
})
```

**Comment by tommy-codez** [comment] 2021-10-20 09:23
Hi there,
it seems this doesnt work anymore in current version (tested on 3.0.0-beta.23)

**Comment by acstll** [comment] 2021-11-01 12:33
Hey @tommy-codez I can confirm this is a bug. This is caused by the event name refactor we did not long ago, we missed one place that required action: https://github.com/telekom/scale/blob/main/packages/components/src/components/modal/modal.tsx#L132

We will fix this and cut a new release.

In the meantime, listening for `scale-before-close` (kebab case) will work.

Thanks again!

**Comment by tommy-codez** [comment] 2021-11-04 10:07
Hi @acstll ,

hm can you guide me :)

at the moment we use this

`    <ScaleModal
      heading={modalTitle}
      size="small"
      opened={modalOpen}
      id="confirmation-modal"
      onScaleBeforeClose={(event) => {
        if (event.detail.trigger === "BACKDROP") {
          event.preventDefault();
        }
      }}
      onScaleClose={declineAction}
    >`

How can I do it now?

**Comment by acstll** [comment] 2021-11-04 10:16
Sure!

You can try with `onScale-before-close`.

```jsx
<ScaleModal
  {...otherProps}
  onScale-before-close={(event) => { if (event.detail.trigger === "BACKDROP") { event.preventDefault(); } }}
  onScaleClose={declineAction}>
```

(Weird as hell, but should work (https://github.com/telekom/scale/issues/625#issuecomment-946503448))

**Comment by acstll** [comment] 2021-11-11 09:09
The "legacy" `scaleBeforeClose` event should be working as expected again in the latest beta 29 🙂

**Closed by acstll** 2021-11-11 09:09 UTC
Labels: bug, feature
