### ISSUE TITLE
Overlapping Label/Value in DateField Component

### ISSUE THREAD

**Issue by tommy-codez** [telekom/scale#440] opened 2021-07-08 08:41 UTC
Hi there,

I am not sure if this a react specific issue or if its reproducable.

If the value of date Field is set with a state value
 ( for example value={state.validFrom} ) 
the label/value is overlapping.

![grafik](https://user-images.githubusercontent.com/66920189/124890007-e5206400-dfd7-11eb-9045-52abaf17f35a.png)

This doesnt happen when the value is set with a direct value - like 
(value={"2021-07-07"})

I assume there is a problem with rerendering ?!

greetings,

**Comment by Lalaluka** [comment] 2021-07-08 09:57
I can't reproduce your behavior😅
I tried a function component and a class component with:
React 17
Scale/React-components both: 3.0.0-beta.15

My Class-based component looks like this:
```
import './App.css';
import React, { Component } from 'react';
import { ScaleDatePicker } from '@telekom/scale-components-react';


class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      test: "2020-12-31"
    }
  }
  render() {
    return (
      <div className="App">
        <scale-date-picker label="Helper Text" value={this.state.test}></scale-date-picker>
        <ScaleDatePicker label="Helper Text" value={this.state.test}></ScaleDatePicker>
      </div>
    );
  }
}

export default App;
```

Both simple WebComponents and the React extensions work as intended.
![Bildschirmfoto 2021-07-08 um 11 54 20](https://user-images.githubusercontent.com/26364692/124902682-747f4480-dfe3-11eb-9649-9bc7081f49af.png)

Do you have the Scale CSS set properly? Your Fonts don't look like TeleNeo to me.
Or do you have some example code?

**Comment by tommy-codez** [comment] 2021-07-08 10:33
Thank you @Lalaluka  for your support. I will recheck the fonts/CSS, but it should be TeleNeo.

We use the date fields in a modal dialog where the initial value are empty strings, but the state changes during opening - perhaps its a timing issue ?! - I will recheck

```
 const openNewModal = () => {
    var tzoffset = emptyCompanyCode.validFrom.getTimezoneOffset() * 60000;
    var localISOTime = new Date(
      emptyCompanyCode.validFrom.getTime() - tzoffset
    );

    setState({
      ...state,
      modalOpen: true,
      companyCode: emptyCompanyCode,
      errors: emptyValidationErrors,
      validFrom: localISOTime.toISOString().split("T")[0],
      validTo: "",
      created: "",
      modified: "",
      modalTitle: t("companycode.newModal.title"),
      warningMessages: [],
    });
  };
```

**Comment by Lalaluka** [comment] 2021-07-08 11:14
Ah now we are getting somewhere ✌️
![Bildschirmfoto 2021-07-08 um 13 12 08](https://user-images.githubusercontent.com/26364692/124912339-1e63ce80-dfee-11eb-96c3-f47d0fffdbd4.png)
This is not React specific and can be reproduced with plain js.
For example like this:
```
<scale-date-picker label="Helper Text" id="Test" value=""></scale-date-picker>
<script>
  setTimeout(()=>{
    document.getElementById('Test').setAttribute("value", "2020-12-31")
  }, 6000)
</script>
```

I'll take a look if I can find the error in the Components code.

**Comment by Lalaluka** [comment] 2021-07-08 11:47
Just wrote a quick PR which should fix the problem.

**Comment by acstll** [comment] 2021-07-09 08:54
Thank you both! 🙏 

Checking the PR right away!

**Comment by acstll** [comment] 2021-07-15 13:05
Fixed in https://github.com/telekom/scale/pull/441

**Closed by acstll** 2021-07-15 13:05 UTC
Labels: bug
